apiVersion: v1
data:
  main.go: |-
    package main

    import (
      "fmt"
      "log"
      "net/http"
      "os"
    )

    func main() {
      log.Println("Starting listening on port " + os.Args[1])
      http.HandleFunc("/", handler) // each request calls handler
      log.Fatal(http.ListenAndServe("0.0.0.0:"+os.Args[1], nil))
    }

    // handler echoes the Path component of the requested URL.
    func handler(w http.ResponseWriter, r *http.Request) {
      fmt.Fprintf(w, "URL.Path = %q\n", r.URL.Path)
    }
kind: ConfigMap
metadata:
  name: go-script
  namespace: default
